{{- if .Values.ingress.enabled -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "guardllama.fullname" . }}-web
  labels:
    {{- include "guardllama.labels.web" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.acme }}
    cert-manager.io/issuer: '{{ include "guardllama.fullname" . }}-acme-issuer'
    {{- else }}
    cert-manager.io/issuer: '{{ include "guardllama.fullname" . }}-selfsigned-issuer'
    {{- end }}
    {{- if and (eq .Values.ingress.className "traefik") .Values.ingress.redirectHttps }}
    traefik.ingress.kubernetes.io/router.middlewares: '{{ .Release.Namespace }}-{{ include "guardllama.fullname" . }}-secure-headers@kubernetescrd'
    {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  {{- with .Values.ingress.hosts }}
  - hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    secretName: web-server-cert
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "guardllama.fullname" . }}-web
                port:
                  number: 80

---

{{- if and (eq .Values.ingress.className "traefik") .Values.ingress.redirectHttps -}}

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: '{{ include "guardllama.fullname" . }}-secure-headers'
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000

{{- end }}

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: '{{ include "guardllama.fullname" . }}-acme-issuer'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: acme@guardllama.net
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class:  traefik

{{- end }}
