apiVersion: v1
kind: Service
metadata:
  name: {{ include "guardllama.fullname" . }}-webhook
  labels:
    {{- include "guardllama.labels.ctrl" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "guardllama.selectorLabels.ctrl" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "guardllama.fullname" . }}-web
  labels:
    {{- include "guardllama.labels.web" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "guardllama.selectorLabels.web" . | nindent 4 }}
