apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ include "guardllama.fullname"
      . }}-serving-cert'
  name: '{{ include "guardllama.fullname" . }}-mutating-webhook-configuration'
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "guardllama.fullname" . }}-webhook'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-tunnel-guardllama-net-v1-tunnel
  failurePolicy: Fail
  name: mtunnel.kb.io
  rules:
  - apiGroups:
    - tunnel.guardllama.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tunnels
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ include "guardllama.fullname"
      . }}-serving-cert'
  name: '{{ include "guardllama.fullname" . }}-validating-webhook-configuration'
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "guardllama.fullname" . }}-webhook'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-tunnel-guardllama-net-v1-tunnel
  failurePolicy: Fail
  name: vtunnel.kb.io
  rules:
  - apiGroups:
    - tunnel.guardllama.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tunnels
  sideEffects: None
