# permissions for end users to edit tunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tunnel-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: guardllama
    app.kubernetes.io/part-of: guardllama
    app.kubernetes.io/managed-by: kustomize
  name: tunnel-editor-role
rules:
- apiGroups:
  - tunnel.guardllama.net
  resources:
  - tunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tunnel.guardllama.net
  resources:
  - tunnels/status
  verbs:
  - get
